name: Update Naukri Profile

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minute
  workflow_dispatch:

jobs:
  update_naukri:
    runs-on: [self-hosted, windows-latest, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      
     

      - name: Install dependencies
        run: npm install    
      - name: Install Playwright Browsers
        run: npx playwright install chromium
          
      - name: Run Naukri agent
        run: node agent.js
        env:
          NAUKRI_USER: ${{ secrets.NAUKRI_USER }}
          NAUKRI_PASS: ${{ secrets.NAUKRI_PASS }}
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: Naukri-screensots
          path: 
            01.png
            

         
          
        
