name: Update Naukri Profile

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minute
  workflow_dispatch:

jobs:
  update_naukri:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      
      - name: Install Chromium
        run: 
          sudo apt-get update 
          sudo apt-get install -y chromium-browser||
          sudo apt-get install -y chromium
          which chromium-browser|| which chromium||
          echo"chromium not found"

      - name: Install dependencies
        run: npm install    
          
      - name: Run Naukri agent
        
        env:
          NAUKRI_USER: ${{ secrets.NAUKRI_USER }}
          NAUKRI_PASS: ${{ secrets.NAUKRI_PASS }}
        run: node agent.js