name: Update Naukri Profile

on:
  schedule:
    - cron: "*/40  * * * *"  # Runs every 40 minutes
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_naukri:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install    
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: "Decoder"
        shell: pwsh
        run: |
          .\decoder.ps1
          
      - name: Run Naukri agent
        run: node agent.js
        env:
          NAUKRI_USER: ${{ secrets.NAUKRI_USER }}
          NAUKRI_PASS: ${{ secrets.NAUKRI_PASS }}
      - name: "List directory"
        shell: pwsh
        run: |
          dir
        if: ${{ always() }}
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Naukri-screensots
          path: |
            **/*.png
            

         
          
        
